#spring:
#  datasource:
##    url: dbc:oracle:thin:@10.199.5.21:1522:erped1
##    username: hjadmin
##    password: hjadmin
#  url: jdbc:oracle:thin:@10.199.5.21:1522:erped1
#  username: hjadmin
#  password: hjadmin
#  driver-class-name :  oracle.jdbc.driver.OracleDriver
#
#  jpa:
#  hibernate:
##      ddl-auto: update
#  ddl-auto: update
#  format_sql: true
#  dialect: org.hibernate.dialect.Oracle10gDialect